### ISSUE TITLE
Explosive bullets does not show hit numbers on everything it hits

### ISSUE THREAD

**Issue by Loerad** [OtagoPolytechnic/Duck#25]
The way the bullets are coded is by simply expanding the hitbox of the bullet for a frame to calculate if anything else hits it and then does damage. This either needs to be rewritten when we add VFX to the items like an explosion effect or needs to have another call for the damage number text in there somewhere.

**Comment by PBWiseman** [comment]
Need to do testing to see if this is actually doing the damage or not. Hard to tell

**Comment by PBWiseman** [comment]
As the explosive bullets are totally non-functional this issue is going to be folded into the work to add our WIP upgrades.
