### ISSUE TITLE
Item UI can be clicked over

### ISSUE THREAD

**Issue by AlexReidNZ** [OtagoPolytechnic/Duck#3]
If player is clicking too fast they can click through the item choice.

Add a item confirmation popup to avoid this?

**Comment by PBWiseman** [comment]
This has been improved by only adding the click event when the window comes up. This means that if the user is holding the fire button down and then releases it on an item it won't select. This still doesn't solve the issue of rapid fire clicking. That would likely require either a confirmation button or delaying activating the buttons for a second.
