### ISSUE TITLE
Static variables are not reset when exiting to the main menu

### ISSUE THREAD

**Issue by AlexReidNZ** [OtagoPolytechnic/Duck#43]
**Describe the bug**
When the player gets a game over, the static variables for the game such as the enemy stat multipliers are not reset.

**To Reproduce**
1. Play the game until you get a game over
2. Return to main menu
3. Play again
4. Enemies will have a very large amount of health

**Expected behavior**
The enemy health should be at a reasonable amount when restarting the game.

**Additional context**
This should be a simple fix, simply call the ResetVariables() method from the GameManager script when returning to the main menu.

**Comment by PBWiseman** [comment]
Getting fixed in #53
